### ISSUE TITLE
Posts disappeared with update? 

### ISSUE THREAD

**Issue by sfxworks** [huyb1991/hugo-lamp#80]
Hi there,

I changed to version `v0.76.3` a while ago. I can't remember what I had before. Though I do know that for some reason it can't see any new posts.

The sidebar and images load just fine. Though I do not see any posts. It just says to generate a new one with `hugo new post`. Though even with that they aren't there. 

My directory is pretty generic.

```
├───archetypes
├───content
│   └───posts
├───data
├───layouts
├───public
│   ├───fonts
│   ├───img
│   ├───page
│   │   └───1
│   ├───post
│   │   ├───how-to-access-files-using-winscp
│   │   ├───how-to-access-minecraft-server-files
│   │   ├───how-to-create-a-minecraft-server
│   │   ├───how-to-setup-mcsh
│   │   └───page
│   │       └───1
│   ├───posts
│   │   └───page
│   │       └───1
│   └───support
│       ├───categories
│       │   └───page
│       │       └───1
│       ├───servertypes
│       │   └───page
│       │       └───1
│       └───tags
│           └───page
│               └───1
├───resources
│   └───_gen
│       ├───assets
│       └───images
├───static
│   └───img
└───themes
    └───hugo-lamp
        ├───.git
        │   ├───hooks
        │   ├───info
        │   ├───logs
        │   │   └───refs
        │   │       ├───heads
        │   │       └───remotes
        │   │           └───origin
        │   ├───objects
        │   │   ├───info
        │   │   └───pack
        │   └───refs
        │       ├───heads
        │       ├───remotes
        │       │   └───origin
        │       └───tags
        ├───archetypes
        ├───docs
        ├───exampleSite
        │   └───content
        │       ├───amp
        │       ├───hugo
        │       └───post
        ├───images
        ├───layouts
        │   ├───partials
        │   ├───post
        │   ├───shortcodes
        │   └───_default
        └───node_modules
            └───.bin
```

```toml
baseURL = "https://example.net/support"
languageCode = "en-us"
title = "Example"
theme = "hugo-lamp"

[[menu.main]]
  name = "Discord / Contact"
  weight = 1
  identifier = "hugo"
  url = "https://discord.gg/vzwCs8K"
[[menu.main]]
  name = "Plans"
  weight = 2
  identifier = "amp"
  url = "https://example.net/plans/index.html"

[params]
  mainSections = ["posts"]
  subtitle = "Support for our various services."
  author = "Samuel Walker"
  logo = "/support/img/icon-transparent.svg"
  description = "Support and articles."
  paginate = 10

[taxonomies]
  category = "/support/categories"
  servertype = "/support/servertypes"
  tag = "/support/tags"
  ```
